# Co-expression analyses

Building from the example here https://docs.pymc.io/notebooks/LKJ.html and here https://github.com/aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3/blob/master/Chp_13.ipynb. And http://www.statsmodels.org/0.6.1/_modules/statsmodels/stats/moment_helpers.html

In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
import numpy as np
import pandas as pd
import pymc3 as pm
import theano.tensor as tt
import toyplot
from statsmodels.stats.moment_helpers import corr2cov, cov2corr

In [3]:
import h5py
import dask.array as da

## H5py and Dask/ reading in data

#### working w/ prof on h5py.

In [23]:
import h5py

# opening a file handle
with h5py.File("db.h5", 'w') as io5:
    
    # initializing an empty h5 database
    nrows = 1000000
    ncols = 50000
    db = io5.create_dataset(name='screads', size=(nrows, ncols), dtype=np.float64, compression='gzip')

    # iterate over chunks of the input data and fill in the db
    ## grab 20K lines of data
    x = 6
    chunks = 20000
    
    bigdata = open("bigdata.csv", 'r')
    for chunk in range(x, nrows, chunks):

        # fill the array
        listdata = []
        for line in range(chunk):
            listdata.append(bigdata.readline().split("\t"))
        
        # convert list of 20K lines to array of floats
        data = np.array(listdata).astype(np.float64)
        
        # stick into db
        db[chunk:chunk+chunks, :] = data
        
    bigdata.close()

In [ ]:
with h5py.File("db.h5", 'r') as io5:
    # grab columns 4-6
    data = io5["screads"][:, [20, 56, 200, 204, 300]].T
    
    ## do something with data...
    # fit pymc3 model for this question
    
    # do the next wquestion
    data = io5["screads"][:, ...]
    

In [7]:
# get gene names from metadata lines
with gzip.open("C:\\Users\\Alexander\\PDSB\\project\\GSE103322_HNSCC_all_data.txt.gz", 'r') as indata:
    for i in range(5):
        line = indata.readline().decode()
        for ele in line.split('\t'):
            print (i)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2


3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3


3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3


4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4


In [1]:
import gzip

listdata = []
with gzip.open("C:\\Users\\Alexander\\PDSB\\project\\GSE103322_HNSCC_all_data.txt.gz") as indata:
    for i in range(10):
        listdata.append(indata.readline().decode())

In [2]:
range(10)

range(0, 10)

In [10]:
cellnames = listdata[0].strip().split('\t')

'HN28_P15_D06_S330_comb'

In [40]:
meta1 = listdata[1].strip().split("\t")
ameta1 = np.array(meta1[1:]).astype(int)
ameta1

array([1, 1, 1, ..., 0, 0, 0])

In [43]:
cancer = np.array(listdata[3].split("\t")[1:]).astype(int)
cancer

array([0, 0, 1, ..., 1, 1, 1])

In [52]:
genes = np.array([i.strip().split('\t')[1:] for i in listdata[6:]])
genes = genes.astype(float)
genes


array([[ 0.     ,  0.     ,  0.42761, ...,  0.     ,  0.     ,  0.     ],
       [ 6.0037 ,  7.3006 ,  7.2885 , ...,  6.8439 ,  6.8676 ,  6.3146 ],
       [ 0.     ,  0.     ,  0.     , ...,  3.2863 ,  0.     ,  3.5905 ],
       [ 0.     ,  0.     ,  0.     , ...,  0.     ,  0.     ,  0.     ]])

### peeking at data w/ pandas.

In [21]:
edf = pd.read_csv('C:\\Users\\Alexander\\PDSB\\project\\test.txt.gz',sep="\t")
edf.shape

(9, 5903)

In [22]:
smol = edf.iloc[0:9,0:9].copy()
print(smol)

                       Unnamed: 0 HN28_P15_D06_S330_comb  \
0      processed by Maxima enzyme                      1   
1                      Lymph node                      1   
2      classified  as cancer cell                      0   
3  classified as non-cancer cells                      1   
4            non-cancer cell type             Fibroblast   
5                      'C9orf152'                      0   
6                         'RPS11'                 6.0037   
7                         'ELMO2'                      0   
8                       'CREB3L1'                      0   

  HN28_P6_G05_S173_comb  HN26_P14_D11_S239_comb HN26_P14_H05_S281_comb  \
0                     1                 1.00000                      1   
1                     0                 1.00000                      1   
2                     0                 1.00000                      0   
3                     1                 0.00000                      1   
4            Fibroblast      

#### Loading in and playing around with a truncated form of the data as a numpy array.

In [11]:
cols = range(1,101,5)
print(cols)

range(1, 101, 5)


In [12]:
gem = np.loadtxt('C:\\Users\\Alexander\\PDSB\\project\\test.txt.gz', skiprows=6, usecols = cols)

In [13]:
gem.shape

(4, 20)

In [14]:
gem

array([[ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 6.0037,  6.9548,  6.0752,  5.2684,  7.1526,  7.3064,  7.1426,
         7.9266,  7.5688,  7.7021,  5.6458,  6.1988,  7.5317,  6.1121,
         6.3683,  7.8509,  6.7936,  5.7059,  7.2721,  4.861 ],
       [ 0.    ,  0.    ,  0.    ,  3.3842,  0.    ,  2.1299,  0.    ,
         0.    ,  0.    ,  3.2478,  0.    ,  0.    ,  0.    ,  5.0812,
         0.    ,  0.    ,  0.    ,  2.6406,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ]])

#### Trying to use h5py...

In [65]:
io5 = h5py.File('testdata.h5', 'w')
io5.create_dataset(name ='test', data = gem)

io5.close()

In [66]:
for cols in range(0,100,5):
    print(list(range(cols,cols+5)))

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[10, 11, 12, 13, 14]
[15, 16, 17, 18, 19]
[20, 21, 22, 23, 24]
[25, 26, 27, 28, 29]
[30, 31, 32, 33, 34]
[35, 36, 37, 38, 39]
[40, 41, 42, 43, 44]
[45, 46, 47, 48, 49]
[50, 51, 52, 53, 54]
[55, 56, 57, 58, 59]
[60, 61, 62, 63, 64]
[65, 66, 67, 68, 69]
[70, 71, 72, 73, 74]
[75, 76, 77, 78, 79]
[80, 81, 82, 83, 84]
[85, 86, 87, 88, 89]
[90, 91, 92, 93, 94]
[95, 96, 97, 98, 99]


In [69]:
with h5py.File('smoltestdata.h5', 'w') as io5:
    db = io5.create_dataset(name = "smol", shape=(100,), dtype='i8')

for cols in range(1, 101, 5):
    print(list(range(cols,cols+5)))
    with np.loadtxt('C:\\Users\\Alexander\\PDSB\\project\\test.txt.gz', skiprows=6, usecols = cols) as data:
            db['singlecells'][:,] #also tried without ['singlecells']; what is the missing attribute?

[1, 2, 3, 4, 5]


AttributeError: __enter__

In [70]:
with h5py.File('bigdata.h5', 'w') as io5:
    db = io5.create_dataset(name = "big", shape=(5902,), dtype='i8')

for cols in range(1, 101, 5):
    print(list(range(cols,cols+5)))
    with np.loadtxt('C:\\Users\\Alexander\\PDSB\\project\\GSE103322_HNSCC_all_data.txt.gz', skiprows=6, usecols = cols) as data:
            db['singlecells'][:,]

[1, 2, 3, 4, 5]


AttributeError: __enter__

No dice. Perhaps try some stuff using examples from the web (https://stackoverflow.com/questions/25655588/incremental-writes-to-hdf5-with-h5py)

path = '/tmp/out.h5'
os.remove(path)
with h5py.File(path, "a") as f:
    dset = f.create_dataset('voltage284', (10**5,), maxshape=(None,),
                            dtype='i8', chunks=(10**4,))
    dset[:] = np.random.random(dset.shape)        
    print(dset.shape)
    # (100000,)

    for i in range(3):
        dset.resize(dset.shape[0]+10**4, axis=0)   
        dset[-10**4:] = np.random.random(10**4)
        print(dset.shape)
        # (110000,)
        # (120000,)
        # (130000,)

In [4]:
import os

In [7]:
path = 'C:\\Users\\Alexander\\PDSB\\project\\testnew.h5'

In [20]:
os.remove(path)

In [16]:
gem.shape

(4, 20)

In [19]:
with h5py.File(path, "a") as f:
    dset = f.create_dataset('testnew', (4,20), maxshape=(None,),
                            dtype='i8', chunks=(4,))
    dset[:] = np.random.random(dset.shape)        
    print(dset.shape)

ValueError: "chunks" must have same rank as dataset shape

try with bigger/full dataset?

### Trying pymc3 on my gene expression matrix.

Most of this code is influenced by the simulation notebook.

In [6]:
#x = data
#xsize = x.shape[1]
#xmeans = x.mean(axis=0)

In [8]:
cols = range(1,5903,13)
#exclude first col (string gene names)
#selecting 454 cells at random (5902/13 = 454)

In [9]:
cols = range(1,5903,13)
gem = np.loadtxt('C:\\Users\\Alexander\\PDSB\\project\\GSE103322_HNSCC_all_data.txt.gz', skiprows=6, usecols = cols)

In [11]:
gem.shape

(23686, 454)

#### remove rows with all 0s

In [12]:
xtmp = gem[~np.all(gem == 0, axis=1)]
print(xtmp.shape)
print(xtmp)

(20146, 454)
[[ 0.        0.        0.       ...,  0.        0.        0.      ]
 [ 6.0037    5.9077    6.3759   ...,  6.5082    6.0536    6.6986  ]
 [ 0.        0.        0.       ...,  0.        0.53107   0.      ]
 ..., 
 [ 0.        0.        0.       ...,  3.6196    5.3366    5.3724  ]
 [ 0.062122  0.086784  0.21039  ...,  4.4697    6.521     6.1847  ]
 [ 0.        0.        0.       ...,  0.        0.        0.      ]]


#### try to run on only highest? highest 10 rows?

In [13]:
highest = np.argpartition(xtmp, -10)[-10:]

In [14]:
print(highest.shape)
print(xtmp.shape)

(10, 454)
(20146, 454)


In [18]:
print(highest)
#i believe these are the indices of the 10 highest row values in each column... unsorted

[[227 226 452 ..., 252 152 453]
 [162 226 452 ...,  49 438 182]
 [244 226   2 ..., 329 241 357]
 ..., 
 [418   0   2 ..., 424 266 429]
 [352   0   2 ..., 369 277 379]
 [228 226 452 ...,  32 152 453]]


In [20]:
highest[:,0]

array([227, 162, 244, 227, 295, 177, 325, 418, 352, 228], dtype=int64)

In [19]:
xtmp[227,]

array([ 3.5657  ,  0.28806 ,  3.5346  ,  4.8973  ,  0.      ,  0.      ,
        0.      ,  1.8992  ,  0.      ,  0.      ,  3.5175  ,  5.0494  ,
        0.      ,  0.      ,  0.      ,  5.7191  ,  1.125   ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  5.2076  ,
        0.      ,  0.      ,  0.      ,  5.3012  ,  0.      ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
        6.1047  ,  6.0159  ,  0.      ,  0.      ,  4.8649  ,  0.      ,
        0.      ,  0.      ,  0.75958 ,  0.      ,  5.0938  ,  4.7647  ,
        5.3827  ,  0.      ,  0.      ,  5.988   ,  0.      ,  0.      ,
        0.      ,  0.24001 ,  0.      ,  0.      ,  0.      ,  0.      ,
        0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  2.8844  ,
        0.      ,  4.1053  ,  0.      ,  0.      , 

In [16]:
xtmphi = xtmp[highest,]

In [17]:
print(xtmphi.shape)
print(xtmphi)

(10, 454, 454)
[[[ 3.5657    0.28806   3.5346   ...,  0.        0.        2.8584  ]
  [ 0.        0.        0.       ...,  0.        0.        0.      ]
  [ 0.        0.        4.5634   ...,  0.        0.        0.      ]
  ..., 
  [ 5.8124    5.7762    4.5733   ...,  7.6815    8.4493    8.2117  ]
  [ 0.        0.        0.       ...,  0.        0.        0.      ]
  [ 0.        0.        0.       ...,  0.        0.        0.      ]]

 [[ 0.        0.        0.       ...,  0.        0.        0.      ]
  [ 0.        0.        0.       ...,  0.        0.        0.      ]
  [ 0.        0.        4.5634   ...,  0.        0.        0.      ]
  ..., 
  [ 0.        0.        0.57821  ...,  0.        0.        0.      ]
  [ 0.        0.        0.       ...,  2.7849    0.        0.      ]
  [ 0.        0.        0.       ...,  0.        0.        0.      ]]

 [[ 0.        0.        0.       ...,  0.        0.        0.      ]
  [ 0.        0.        0.       ...,  0.        0.        0.      ]

In [ ]:
with pm.Model() as model:
    
    # distribution to draw stds from (not a rv for now) but is a wide prior
    stds = pm.HalfCauchy.dist(2)
    
    # sample correlations by drawing halfCauchy std values
    # eta=1 is uniform corrs, eta>1 puts more weight on corr=0.
    packed = pm.LKJCholeskyCov('packed_chol', n=xsize, eta=1., sd_dist=stds)
    
    # expand correlation matrix and define VCV as dot product
    chol = pm.expand_packed_triangular(xsize, packed)
    cov = pm.Deterministic('cov', chol.dot(chol.T))
    sigma = pm.Deterministic('sigma', tt.sqrt(tt.diag(cov)))

    # draw the means from a normal with starting values from observed means
    # set this mean and std of this dist according to your data, or it could
    # be made into a random variable to be fit.
    means = pm.Normal('means', 5, 5, shape=xsize, testval=xmeans)
    obs = pm.MvNormal('obs', means, chol=chol, observed=x)

I didn't end up running pymc3 on this. Ultimately, I don't think just picking the 10 highest genes will be very useful or informative. Need to find some way to select a smaller subset of genes: "supervised" approach with feeding in gene names/row indices?